version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    groups:
      rustcrypto:
        patterns:
          - "ecdsa"
          - "p256"
          - "p384"
          - "p521"
          - "sha2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
