[package]
name = "tee-attestation-verification-cose"
version = "1.0.2"
edition = "2021"
repository = "https://github.com/microsoft/TEE-Attestation-Verification"
keywords = ["confidentiality", "sev-snp", "tpm"]
description = "COSE signing and verification helpers for TEE attestation verification"
authors = ["Max Tropets", "Chris Jensen"]
license = "MIT"

[features]
default = []
pqc = []

[dependencies]
openssl-sys = "0.9"
cborrs = { git = "https://github.com/project-everest/everparse.git", rev = "f4cd5ffa183edd5cc824d66588012bcf8d0bdccd" } # v2026.02.25
cborrs-nondet = { git = "https://github.com/project-everest/everparse.git", rev = "f4cd5ffa183edd5cc824d66588012bcf8d0bdccd" } # v2026.02.25
