name: "Crypto CI"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-crypto-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  native:
    name: Native OpenSSL backend
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Build with OpenSSL backend
        run: cargo build --manifest-path crypto/Cargo.toml --no-default-features --features crypto_openssl

      - name: Test with OpenSSL backend
        run: cargo test --manifest-path crypto/Cargo.toml --no-default-features --features crypto_openssl -- --nocapture

      - name: Check compliant default dependencies
        run: scripts/check-crypto-default-dependencies.sh

      - name: Test compliant default
        run: cargo test --manifest-path crypto/Cargo.toml -- --nocapture

  windows:
    name: Windows CNG backend
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install rust
        run: |
          rustup update stable
          rustup default stable

      - name: Test with Windows CNG backend
        run: cargo test --manifest-path crypto/Cargo.toml --no-default-features --features crypto_windows -- --nocapture

      - name: Test compliant default
        run: cargo test --manifest-path crypto/Cargo.toml -- --nocapture

  wasm:
    name: WASM WebCrypto backend
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Setup WASM tooling
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack --version 0.13.1 --locked

      - name: Check WebCrypto backend
        run: cargo check --manifest-path crypto/Cargo.toml --target wasm32-unknown-unknown --no-default-features --features crypto_webcrypto

      - name: Check compliant default
        run: cargo check --manifest-path crypto/Cargo.toml --target wasm32-unknown-unknown

      - name: Test WebCrypto backend
        working-directory: crypto
        run: wasm-pack test --node --no-default-features --features crypto_webcrypto

      - name: Test compliant default
        working-directory: crypto
        run: wasm-pack test --node
