name: "CACI attestation verification CI"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-caci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  native:
    name: Native OpenSSL backend
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install rust
        run: |
          rustup update stable && rustup default stable

      - name: Build with OpenSSL backend
        run: cargo build --manifest-path caci/Cargo.toml --no-default-features --features crypto_openssl

      - name: Test with OpenSSL backend
        run: cargo test --manifest-path caci/Cargo.toml --no-default-features --features crypto_openssl -- --nocapture
